# Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import cv2 as cv
import typing as t
import pandas as pd
import pathlib as pb
import numpy as np
import sklearn as sk
import random as rnd
import matplotlib.pyplot as plt
import torch
import torchvision as tv
import torch.utils.data as data
from torch import Tensor
import lightning.pytorch as pl

In [3]:
import domino.data
import domino.game
import domino.model
import domino.vision
import domino.preprocess

# Environment Setup

In [4]:
# Predefined expected paths
ROOT_PATH: pb.Path = pb.Path('..')
DATA_PATH: pb.Path = ROOT_PATH / 'data'
CACHE_DIR: pb.Path = ROOT_PATH / '.cache'
MODEL_DIR: pb.Path = ROOT_PATH / '.model'
SKLRN_DIR: pb.Path = MODEL_DIR / 'sklearn'
TORCH_DIR: pb.Path = MODEL_DIR / 'torch'

# Pretrained model weights
FOREST_MODEL_PATH: pb.Path = SKLRN_DIR / 'balanced-random-forest.joblib'
RESNET_MODEL_PATH: pb.Path = TORCH_DIR / 'resnet50-finetune-train.ckpt'

# Main dataset for the given tasks
HELP_PATH: pb.Path       = DATA_PATH      / 'help'
TEST_PATH: pb.Path       = DATA_PATH      / 'test'
TRAIN_PATH: pb.Path      = DATA_PATH      / 'train'
VALID_PATH: pb.Path      = DATA_PATH      / 'valid'

# Auxiliary dataset made of grid cell patches
CELL_DATA_PATH: pb.Path  = DATA_PATH      / 'cell'
CELL_TRAIN_PATH: pb.Path = CELL_DATA_PATH / 'train'
CELL_TEST_PATH: pb.Path  = CELL_DATA_PATH / 'test'

# Obtain deterministic results
SEED = 42
rnd.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
generator: torch.Generator = torch.Generator().manual_seed(SEED)

# Configure current environment
torch.hub.set_dir(CACHE_DIR)
torch.set_float32_matmul_precision('medium')

In [5]:
# Load datasets for the task
train_dataset = domino.data.DDDGameDataset(TRAIN_PATH, train=True)
valid_dataset = domino.data.DDDGameDataset(VALID_PATH, train=True)
test_dataset  = domino.data.DDDGameDataset(TEST_PATH, train=False)

# Construct task solver
task_path: pb.Path = VALID_PATH
task_solver = domino.game.DoubleDoubleDominoesTask(
    dataset_path=task_path,
    classifier_path=RESNET_MODEL_PATH,
    cell_classifier='resnet',
    show_matrix=False,
    train=False,
)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [6]:
task_solver.task_regular.solve()

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/invokariman/.cache/pypoetry/virtualenvs/double-double-dominos-R-JT3pI_-py3.10/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:430: PossibleUserWarning: The dataloader, predict_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 67.12it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 242.06it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 242.35it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 240.67it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 243.17it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 239.15it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 242.60it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 242.40it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 237.12it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 238.42it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 240.55it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 7 7 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 239.88it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 7 7 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 242.14it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 2 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 7 7 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 237.18it/s]
[[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[3 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 2 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 7 7 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 240.65it/s]
[[0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[3 4 4 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 2 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 7 7 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 7 7 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 239.77it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[3 4 4 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 2 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 6 5 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 7 7 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 243.63it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[3 4 4 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 2 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 6 5 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 0 3 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 240.37it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[3 4 4 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 2 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 6 5 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [5 0 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 0 3 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 242.43it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[3 4 4 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 2 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 6 5 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 0 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [7 0 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [5 0 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 0 3 3 1 1 7 7 7 7 7 7 7 7 7]
 

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 29/29 [00:00<00:00, 238.81it/s]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[3 4 4 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 4 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [7 2 7 7 7 7 7 7 7 7 7 7 7 7 7]
 [2 2 2 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 1 0 0 7 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 0 4 7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 4 3 3 6 6 5 7 7 7 7 7]
 [7 7 7 7 7 3 7 7 7 7 7 7 7 7 7]
 [7 0 0 1 7 5 7 7 7 7 7 7 7 7 7]
 [7 0 7 7 7 5 7 7 7 7 7 7 7 7 7]
 [5 0 7 7 7 1 7 7 7 7 7 7 7 7 7]
 [7 0 3 3 1 1 7 7 7 7 7 7 7 7 7]
 

In [ ]:
game_index = 0
game_turns, game_labels = task_solver.dataset.dataset_regular[game_index]
matrices: t.List[np.ndarray] = [np.full((15, 15), 7)]
state = []

for turn, (game_turn, (_, game_label)) in enumerate(zip(game_turns, game_labels.iterrows())):
    # Infer cell values
    unit_matrix: np.ndarray = task_solver.board2matrix(game_turn)
    changes: t.List[np.ndarray] = (unit_matrix != matrices[-1]).nonzero()
    print((unit_matrix != matrices[-1]).astype(np.float32))
    matrices.append(unit_matrix)

    print('{} - Pred:'.format(turn + 1))
    for change in zip(changes[0], changes[1]):
        print(f'{change[0] + 1}{chr(ord("A") + change[1])}: {unit_matrix[change[0]][change[1]]}')

    print('{} - Truth:'.format(turn + 1))
    print(f'{game_label["pos"][0]}: {game_label["num"][0]}')
    print(f'{game_label["pos"][1]}: {game_label["num"][1]}')
    print()